#!/bin/sh
version=$1
doubleHypenedVersion=$(echo "${version}" | sed -e 's/-/--/')
sed -i "s/version = .*/version = '$version'/" build.gradle
sed -i "s/.*com.github.giulioscattolin:sample.*/    implementation 'com.github.giulioscattolin:sample:$version'/" README.md
sed -i "s/.*Javadoc badge.*/[![Javadoc badge](https:\/\/img.shields.io\/badge\/Javadoc-$doubleHypenedVersion-brightgreen)](https:\/\/javadoc.jitpack.io\/com\/github\/giulioscattolin\/sample\/$version\/javadoc\/)/" README.md